createOrReplace

	table Calendar
		dataCategory: Time

		column Date
			dataType: dateTime
			isKey
			formatString: Long Date

			summarizeBy: none
			sourceColumn: Date

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column Year
			dataType: double
			formatString: 0

			summarizeBy: none
			sourceColumn: Year

			changedProperty = FormatString

			annotation SummarizationSetBy = User

		column 'Month Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Month Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Month
			dataType: string

			summarizeBy: none
			sourceColumn: Month
			sortByColumn: 'Month Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Quarter Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Quarter Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Week of Year'
			dataType: double

			summarizeBy: none
			sourceColumn: Week of Year

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Week of Month'
			dataType: double

			summarizeBy: none
			sourceColumn: Week of Month

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Day
			dataType: double

			summarizeBy: none
			sourceColumn: Day

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Day of Week Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Day of Week Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Day of Year'
			dataType: double

			summarizeBy: none
			sourceColumn: Day of Year

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Day of Week'
			dataType: string

			summarizeBy: none
			sourceColumn: Day of Week
			sortByColumn: 'Day of Week Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Year Month Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Year Month Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Year Month'
			dataType: string

			summarizeBy: none
			sourceColumn: Year Month
			sortByColumn: 'Year Month Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Year Quarter Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Year Quarter Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column Quarter
			dataType: string

			summarizeBy: none
			sourceColumn: Quarter
			sortByColumn: 'Quarter Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Year Quarter'
			dataType: string

			summarizeBy: none
			sourceColumn: Year Quarter
			sortByColumn: 'Year Quarter Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Year Week Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Year Week Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Year Week'
			dataType: string

			summarizeBy: none
			sourceColumn: Year Week
			sortByColumn: 'Year Week Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'HalfYear Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: HalfYear Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Year HalfYear Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Year HalfYear Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column HalfYear
			dataType: string

			summarizeBy: none
			sourceColumn: HalfYear
			sortByColumn: 'HalfYear Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Year HalfYear'
			dataType: string

			summarizeBy: none
			sourceColumn: Year HalfYear
			sortByColumn: 'Year HalfYear Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Fiscal Year'
			dataType: string

			summarizeBy: none
			sourceColumn: Fiscal Year
			sortByColumn: 'Fiscal Year Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Fiscal Month Number'
			dataType: int64
			isHidden
			formatString: 0

			summarizeBy: none
			sourceColumn: Fiscal Month Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

		column 'Fiscal Quarter Number'
			dataType: int64
			isHidden
			formatString: 0

			summarizeBy: none
			sourceColumn: Fiscal Quarter Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

		column 'Fiscal Year Month Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Fiscal Year Month Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Fiscal Year Quarter Number'
			dataType: double
			isHidden

			summarizeBy: none
			sourceColumn: Fiscal Year Quarter Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		column 'Fiscal Quarter'
			dataType: string

			summarizeBy: none
			sourceColumn: Fiscal Quarter
			sortByColumn: 'Fiscal Quarter Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Fiscal Year Quarter'
			dataType: string

			summarizeBy: none
			sourceColumn: Fiscal Year Quarter
			sortByColumn: 'Fiscal Year Quarter Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Fiscal Year Number'
			dataType: int64
			isHidden
			formatString: 0

			summarizeBy: none
			sourceColumn: Fiscal Year Number

			changedProperty = IsHidden

			annotation SummarizationSetBy = User

		column 'Fiscal Month'
			dataType: string

			summarizeBy: none
			sourceColumn: Fiscal Month
			sortByColumn: 'Fiscal Month Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		column 'Fiscal Year Month'
			dataType: string

			summarizeBy: none
			sourceColumn: Fiscal Year Month
			sortByColumn: 'Fiscal Year Month Number'

			changedProperty = SortByColumn

			annotation SummarizationSetBy = Automatic

		partition Calendar-5ad1cbc7-a4b9-43fc-99d2-8f9992deadf0 = m
			mode: import
			source = ```
					let
					    StartDate = #date(StartYear, 1, 1),
					    EndDate = 
					        #date(
					            Date.Year(
					                DateTime.LocalNow()
					            ) + FutureYears, 12, 31),
					    NumberOfDays = Duration.Days(EndDate - StartDate),
					    Dates =
					        List.Dates(
					            StartDate,
					            NumberOfDays + 1,
					            #duration(1, 0, 0, 0)
					        ),
					    #"Converted to Table" =
					        Table.FromList(
					            Dates,
					            Splitter.SplitByNothing(),
					            null,
					            null,
					            ExtraValues.Error
					        ),
					    #"Renamed Columns" =
					        Table.RenameColumns(
					            #"Converted to Table",
					            {
					                {
					                    "Column1",
					                    "FullDateAlternateKey"
					                }
					            }
					        ),
					    #"Changed Type" =
					        Table.TransformColumnTypes(
					            #"Renamed Columns",
					            {
					                {
					                    "FullDateAlternateKey",
					                    type date
					                }
					            }
					        ),
					    #"Inserted Year" =
					        Table.AddColumn(
					            #"Changed Type",
					            "Year",
					            each Date.Year([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Month" =
					        Table.AddColumn(
					            #"Inserted Year",
					            "Month Number",
					            each Date.Month([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Month Name" =
					        Table.AddColumn(
					            #"Inserted Month",
					            "Month",
					            each Date.MonthName([FullDateAlternateKey]),
					            type text
					        ),
					    #"Inserted Quarter" =
					        Table.AddColumn(
					            #"Inserted Month Name",
					            "Quarter Number",
					            each Date.QuarterOfYear([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Week of Year" =
					        Table.AddColumn(
					            #"Inserted Quarter",
					            "Week of Year",
					            each Date.WeekOfYear([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Week of Month" =
					        Table.AddColumn(
					            #"Inserted Week of Year",
					            "Week of Month",
					            each Date.WeekOfMonth([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Day" =
					        Table.AddColumn(
					            #"Inserted Week of Month",
					            "Day",
					            each Date.Day([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Day of Week" =
					        Table.AddColumn(
					            #"Inserted Day",
					            "Day of Week Number",
					            each
					                Date.DayOfWeek(
					                    [FullDateAlternateKey],
					                    1
					                ),
					            type number
					        ),
					    #"Inserted Day of Year" =
					        Table.AddColumn(
					            #"Inserted Day of Week",
					            "Day of Year",
					            each Date.DayOfYear([FullDateAlternateKey]),
					            type number
					        ),
					    #"Inserted Day Name" =
					        Table.AddColumn(
					            #"Inserted Day of Year",
					            "Day of Week",
					            each Date.DayOfWeekName([FullDateAlternateKey]),
					            type text
					        ),
					    #"Inserted Year Month" =
					        Table.AddColumn(
					            #"Inserted Day Name",
					            "Year Month Number",
					            each [Year] * 100 + [Month Number],
					            type number
					        ),
					    #"Inserted Year Month Name" =
					        Table.AddColumn(
					            #"Inserted Year Month",
					            "Year Month",
					            each
					                Text.Combine(
					                    {
					                        [Month],
					                        " ",
					                        Text.From([Year], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Year Quarter" =
					        Table.AddColumn(
					            #"Inserted Year Month Name",
					            "Year Quarter Number",
					            each [Year] * 10 + [Quarter Number],
					            type number
					        ),
					    #"Inserted Quarter Name" =
					        Table.AddColumn(
					            #"Inserted Year Quarter",
					            "Quarter",
					            each
					                Text.Combine(
					                    {
					                        "Q",
					                        Text.From([Quarter Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Year Quarter Name" =
					        Table.AddColumn(
					            #"Inserted Quarter Name",
					            "Year Quarter",
					            each
					                Text.Combine(
					                    {
					                        [Quarter],
					                        " ",
					                        Text.From([Year], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Year Week" =
					        Table.AddColumn(
					            #"Inserted Year Quarter Name",
					            "Year Week Number",
					            each [Year] * 100 + [Week of Year],
					            type number
					        ),
					    #"Inserted Year Week Name" =
					        Table.AddColumn(
					            #"Inserted Year Week",
					            "Year Week",
					            each
					                Text.Combine(
					                    {
					                        "Week",
					                        " ",
					                        Text.From([Week of Year], "en-US"),
					                        " ",
					                        Text.From([Year], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted HalfYear" =
					        Table.AddColumn(
					            #"Inserted Year Week Name",
					            "HalfYear Number",
					            each Number.RoundUp([Quarter Number] / 2),
					            type number
					        ),
					    #"Inserted Year HalfYear" =
					        Table.AddColumn(
					            #"Inserted HalfYear",
					            "Year HalfYear Number",
					            each [Year] * 10 + [HalfYear Number],
					            type number
					        ),
					    #"Inserted HalfYear Name" =
					        Table.AddColumn(
					            #"Inserted Year HalfYear",
					            "HalfYear",
					            each
					                Text.Combine(
					                    {
					                        "HY",
					                        Text.From([HalfYear Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Year HalfYear Name" =
					        Table.AddColumn(
					            #"Inserted HalfYear Name",
					            "Year HalfYear",
					            each
					                Text.Combine(
					                    {
					                        [HalfYear],
					                        " ",
					                        Text.From([Year], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Renamed Columns1" =
					        Table.RenameColumns(
					            #"Inserted Year HalfYear Name",
					            {
					                {
					                    "FullDateAlternateKey",
					                    "Date"
					                }
					            }
					        ),
					    #"Inserted  Fiscal Year" = 
					        Table.AddColumn(
					            #"Renamed Columns1", 
					            "Fiscal Year Number", 
					            each 
					                if [Month Number] >= StartOfFiscalYear
					                    then [Year] + 1
					                    else [Year],
					            Int64.Type
					        ),
					    #"Inserted Fiscal Month" = 
					        Table.AddColumn(
					            #"Inserted  Fiscal Year", 
					            "Fiscal Month Number", 
					            each 
					                if [Month Number] >= StartOfFiscalYear
					                    then [Month Number] - (StartOfFiscalYear - 1)
					                    else [Month Number] + (12 - StartOfFiscalYear+1),
					            Int64.Type
					        ),
					    #"Inserted Fiscal Quarter" = 
					        Table.TransformColumns(
					            Table.AddColumn(
					                #"Inserted Fiscal Month", 
					                "Fiscal Quarter Number", 
					                each 
					                    [Fiscal Month Number] / 3, 
					                    type number
					            ),
					            {
					                {
					                    "Fiscal Quarter Number", 
					                    Number.RoundUp, 
					                    Int64.Type
					                }
					            }
					        ),
					    #"Inserted Fiscal Year Month" =
					        Table.AddColumn(
					            #"Inserted Fiscal Quarter",
					            "Fiscal Year Month Number",
					            each [Fiscal Year Number] * 100 + [Fiscal Month Number],
					            type number
					        ),
					    #"Inserted Fiscal Year Quarter" =
					        Table.AddColumn(
					            #"Inserted Fiscal Year Month",
					            "Fiscal Year Quarter Number",
					            each [Fiscal Year Number] * 10 + [Fiscal Quarter Number],
					            type number
					        ),
					    #"Inserted Fiscal Quarter Name" =
					        Table.AddColumn(
					            #"Inserted Fiscal Year Quarter",
					            "Fiscal Quarter",
					            each
					                Text.Combine(
					                    {
					                        "FQ",
					                        Text.From([Fiscal Quarter Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Fiscal Year Quarter Name" =
					        Table.AddColumn(
					            #"Inserted Fiscal Quarter Name",
					            "Fiscal Year Quarter",
					            each
					                Text.Combine(
					                    {
					                        [Fiscal Quarter],
					                        " ",
					                        Text.From([Fiscal Year Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Fiscal Month Name" =
					        Table.AddColumn(
					            #"Inserted Fiscal Year Quarter Name",
					            "Fiscal Month",
					            each
					                Text.Combine(
					                    {
					                        "FM",
					                        Text.From([Fiscal Month Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Fiscal Year Month Name" =
					        Table.AddColumn(
					            #"Inserted Fiscal Month Name",
					            "Fiscal Year Month",
					            each
					                Text.Combine(
					                    {
					                        [Fiscal Month],
					                        " ",
					                        Text.From([Fiscal Year Number], "en-US")
					                    }
					                ),
					            type text
					        ),
					    #"Inserted Fiscal Year Name" =
					        Table.AddColumn(
					            #"Inserted Fiscal Year Month Name",
					            "Fiscal Year",
					            each
					                Text.Combine(
					                    {
					                        "FY",
					                        Text.From([Fiscal Year Number], "en-US")
					                    }
					                ),
					            type text
					        )
					in
					    #"Inserted Fiscal Year Name"
					```

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation
		
	relationship 32c259e3-9d49-4b35-95f0-d04be7f3e82f
		fromColumn: Sales.Date
		toColumn: Calendar.Date